### PR TITLE
Fix TSAN data races

### LINKED ISSUE #71: TSAN Detected Data Race: Fix or Note as False Positive
The following are list of [tsan detected data races](https://github.com/intel/fpga-runtime-for-opencl/pull/63)

The following happened in threadsupport package (which we should note as false positive, given we don't want to change these third party libraries.

```
WARNING: ThreadSanitizer: data race (pid=714)
  Write of size 4 at 0x559b36f693d4 by thread T4 (mutexes: write M53):
    #0 test_thread(void*) ../lib/acl_threadsupport/test/acl_threadsupport_test.cpp:105 (acl_threadsupport_test+0xa490)

  Previous read of size 4 at 0x559b36f693d4 by main thread:
    #0 threadsupport_threads_Test::testBody() ../lib/acl_threadsupport/test/acl_threadsupport_test.cpp:128 (acl_threadsupport_test+0xaac8)
    #1 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_threadsupport_test+0x1d278)
    #2 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_threadsupport_test+0x1aa94)
    #3 threadsupport_threads_Test::runInThreadOnCopy() <null> (acl_threadsupport_test+0x108ef)
    #4 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_threadsupport_test+0x1d7aa)
    #5 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_threadsupport_test+0x1a9e7)
    #6 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_threadsupport_test+0x1a8f6)
    #7 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_threadsupport_test+0x1d4ba)
    #8 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_threadsupport_test+0x1a873)
    #9 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_threadsupport_test+0x19c4d)
    #10 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_threadsupport_test+0x133ac)
    #11 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_threadsupport_test+0x1354d)
    #12 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_threadsupport_test+0x1367d)
    #13 main ../lib/acl_threadsupport/test/acl_test.cpp:14 (acl_threadsupport_test+0x8c0b)

  Location is global 'threadtest_state' of size 4 at 0x559b36f693d4 (acl_threadsupport_test+0x00000002f3d4)

  Mutex M53 (0x559b36f693e0) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1220 (libtsan.so.0+0x4a616)
    #1 acl_mutex_init ../lib/acl_threadsupport/src/acl_threadsupport.c:97 (acl_threadsupport_test+0x120ec)
    #2 threadsupport_threads_Test::testBody() ../lib/acl_threadsupport/test/acl_threadsupport_test.cpp:115 (acl_threadsupport_test+0xa529)
    #3 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_threadsupport_test+0x1d278)
    #4 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_threadsupport_test+0x1aa94)
    #5 threadsupport_threads_Test::runInThreadOnCopy() <null> (acl_threadsupport_test+0x108ef)
    #6 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_threadsupport_test+0x1d7aa)
    #7 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_threadsupport_test+0x1a9e7)
    #8 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_threadsupport_test+0x1a8f6)
    #9 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_threadsupport_test+0x1d4ba)
    #10 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_threadsupport_test+0x1a873)
    #11 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_threadsupport_test+0x19c4d)
    #12 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_threadsupport_test+0x133ac)
    #13 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_threadsupport_test+0x1354d)
    #14 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_threadsupport_test+0x1367d)
    #15 main ../lib/acl_threadsupport/test/acl_test.cpp:14 (acl_threadsupport_test+0x8c0b)

  Thread T4 (tid=719, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:962 (libtsan.so.0+0x5ea79)
    #1 acl_thread_create ../lib/acl_threadsupport/src/acl_threadsupport.c:50 (acl_threadsupport_test+0x11ed9)
    #2 threadsupport_threads_Test::testBody() ../lib/acl_threadsupport/test/acl_threadsupport_test.cpp:121 (acl_threadsupport_test+0xa781)
    #3 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_threadsupport_test+0x1d278)
    #4 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_threadsupport_test+0x1aa94)
    #5 threadsupport_threads_Test::runInThreadOnCopy() <null> (acl_threadsupport_test+0x108ef)
    #6 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_threadsupport_test+0x1d7aa)
    #7 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_threadsupport_test+0x1a9e7)
    #8 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_threadsupport_test+0x1a8f6)
    #9 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_threadsupport_test+0x1d4ba)
    #10 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_threadsupport_test+0x1a873)
    #11 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_threadsupport_test+0x19c4d)
    #12 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_threadsupport_test+0x133ac)
    #13 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_threadsupport_test+0x1354d)
    #14 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_threadsupport_test+0x1367d)
    #15 main ../lib/acl_threadsupport/test/acl_test.cpp:14 (acl_threadsupport_test+0x8c0b)

SUMMARY: ThreadSanitizer: data race ../lib/acl_threadsupport/test/acl_threadsupport_test.cpp:105 in test_thread(void*)
```

The following are found in our source code which is what we should care about
```
WARNING: ThreadSanitizer: heap-use-after-free (pid=737)
  Read of size 4 at 0x7b3c000003d4 by main thread:
    #0 acl_ref_count<_cl_command_queue*> ../include/acl_util.h:433 (acl_test+0x1263a8)
    #1 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:677 (acl_test+0x1263a8)
    #2 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #3 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #4 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #5 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #6 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #7 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #8 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #9 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #10 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #11 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #12 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #13 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #14 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Previous write of size 8 at 0x7b3c000003d0 by main thread (mutexes: write M44):
    #0 operator delete(void*) ../../../../src/libsanitizer/tsan/tsan_new_delete.cpp:126 (libtsan.so.0+0x8b2c8)
    #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x49040)
    #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x49040)
    #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x49316)
    #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x4a755)
    #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x4a7ad)
    #6 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:675 (acl_test+0x126192)
    #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #9 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #19 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Mutex M44 (0x55817c8c2100) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1220 (libtsan.so.0+0x4a616)
    #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x54382e)
    #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x102eda)
    #3 __libc_csu_init <null> (acl_test+0x556acc)

SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:433 in acl_ref_count<_cl_command_queue*>
==================
==================
WARNING: ThreadSanitizer: heap-use-after-free (pid=737)
  Read of size 4 at 0x7b3c000002e4 by main thread:
    #0 acl_ref_count<_cl_command_queue*> ../include/acl_util.h:433 (acl_test+0x1264c3)
    #1 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:678 (acl_test+0x1264c3)
    #2 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #3 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #4 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #5 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #6 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #7 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #8 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #9 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #10 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #11 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #12 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #13 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #14 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Previous write of size 8 at 0x7b3c000002e0 by main thread (mutexes: write M44):
    #0 operator delete(void*) ../../../../src/libsanitizer/tsan/tsan_new_delete.cpp:126 (libtsan.so.0+0x8b2c8)
    #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x49040)
    #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x49040)
    #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x49316)
    #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x4a755)
    #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x4a7ad)
    #6 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:676 (acl_test+0x12629d)
    #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #9 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #19 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Mutex M44 (0x55817c8c2100) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1220 (libtsan.so.0+0x4a616)
    #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x54382e)
    #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x102eda)
    #3 __libc_csu_init <null> (acl_test+0x556acc)

SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:433 in acl_ref_count<_cl_command_queue*>
==================
==================
WARNING: ThreadSanitizer: heap-use-after-free (pid=737)
  Read of size 8 at 0x7b3c000003c8 by main thread (mutexes: write M44):
    #0 int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&) ../include/acl_util.h:417 (acl_test+0x4a45d)
    #1 acl_command_queue_is_valid(_cl_command_queue*) ../src/acl_command_queue.cpp:553 (acl_test+0x4a45d)
    #2 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:680 (acl_test+0x126600)
    #3 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #4 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #5 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #6 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #7 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #8 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #9 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #10 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #11 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #12 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #13 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #14 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #15 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Previous write of size 8 at 0x7b3c000003c8 by main thread (mutexes: write M44):
    #0 operator delete(void*) ../../../../src/libsanitizer/tsan/tsan_new_delete.cpp:126 (libtsan.so.0+0x8b2c8)
    #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x49040)
    #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x49040)
    #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x49316)
    #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x4a755)
    #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x4a7ad)
    #6 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:675 (acl_test+0x126192)
    #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #9 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #19 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Mutex M44 (0x55817c8c2100) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1220 (libtsan.so.0+0x4a616)
    #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x54382e)
    #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x102eda)
    #3 __libc_csu_init <null> (acl_test+0x556acc)

SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:417 in int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&)
==================
==================
WARNING: ThreadSanitizer: heap-use-after-free (pid=737)
  Read of size 8 at 0x7b3c000002d8 by main thread (mutexes: write M44):
    #0 int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&) ../include/acl_util.h:417 (acl_test+0x4a45d)
    #1 acl_command_queue_is_valid(_cl_command_queue*) ../src/acl_command_queue.cpp:553 (acl_test+0x4a45d)
    #2 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:681 (acl_test+0x12666e)
    #3 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #4 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #5 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #6 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #7 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #8 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #9 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #10 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #11 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #12 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #13 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #14 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #15 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Previous write of size 8 at 0x7b3c000002d8 by main thread (mutexes: write M44):
    #0 operator delete(void*) ../../../../src/libsanitizer/tsan/tsan_new_delete.cpp:126 (libtsan.so.0+0x8b2c8)
    #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x49040)
    #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x49040)
    #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x49316)
    #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x4a755)
    #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x4a7ad)
    #6 acl_command_queue_after_context_release_Test::testBody() ../test/acl_command_queue_test.cpp:676 (acl_test+0x12629d)
    #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x54e3b4)
    #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x54bbd0)
    #9 acl_command_queue_after_context_release_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:622 (acl_test+0x13c1c0)
    #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x54e8e6)
    #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x54bb23)
    #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x54ba32)
    #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x54e5f6)
    #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x54b9af)
    #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x54ad89)
    #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x5444e8)
    #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x544689)
    #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x5447b9)
    #19 main ../test/acl_test.cpp:90 (acl_test+0x4b3f45)

  Mutex M44 (0x55817c8c2100) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1220 (libtsan.so.0+0x4a616)
    #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x54382e)
    #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x102eda)
    #3 __libc_csu_init <null> (acl_test+0x556acc)

SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:417 in int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&)
==================
```

### PR DESCRIPTION
**Pull request by sherry-yuan**
As found in #71, tsan reported several issues in the acl_test

Currently when release command queue are called (which frees the memory) subsequent still checks the values at the same address which cause tsan to report heap-use-after-free.

The test after_context_release are moved upward to be the first test because ctest execute the test in reverse order of how they appear in the cpp file. Given after_context_release will release the command queue, they should be run last, i.e place at the top in the test.cpp file.

Prerequisit for #63 

Closes #71

### CODE REVIEW

**Comment by pcolberg** [comment]
Thanks @sherry-yuan for addressing thread safety!

I am not quite sure I understand the issue yet. The context `context` as well as the command queues `cq0` and `cq1` are created and released locally in test `after_context_release`. Why would their release affect another test executed afterwards? Would this not be considered a bug in the runtime?

**Comment by sherry-yuan** [comment]
> Why would their release affect another test executed afterwards? Would this not be considered a bug in the runtime?

I realized this is not the cause after testing it again (probably things started working after multiple change and lead me into thinking all of them together fix the issue). 

Updated the newest version to not change test order.

File: test/acl_command_queue_test.cpp [hunk 1]
```diff
@@ -387,8 +387,6 @@ MT_TEST(acl_command_queue, create_with_properties) {
     CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
     CHECK_EQUAL(1, acl_ref_count(cq));
     CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
-    CHECK_EQUAL(0, acl_ref_count(cq));
-    ACL_LOCKED(CHECK(!acl_command_queue_is_valid(cq)));
```
Comment (pcolberg) [inline test/acl_command_queue_test.cpp:391]: Now I am wondering, is this also flaged by ASAN?

File: CMakeLists.txt [hunk 2]
```diff
@@ -68,6 +68,18 @@ if(ACL_CODE_COVERAGE)
   endif()
 endif()
 
+# Flag for tsan scans
+option(ACL_TSAN "Build with tsan" OFF)
+message(STATUS "Build with tsan: ${ACL_TSAN}")
+if(ACL_TSAN)
+  if(CMAKE_COMPILER_IS_GNUCXX)
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -ltsan -fsanitize=thread -g -O1 -fno-omit-frame-pointer -fPIC")
+    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -ltsan -fsanitize=thread -g -O1 -fno-omit-frame-pointer -fPIC")
```
Comment (pcolberg) [inline CMakeLists.txt:77]: We use [`-Og` in `Debug` mode](https://github.com/intel/fpga-runtime-for-opencl/blob/8cd410fe9111a1fc9c7c122f54da1fc21c4fa587/CMakeLists.txt#L131-L133) now, would that be sufficient? I believe `-fPIC` is the default for all modes. `-g` is already provided by `Debug` mode; does it make much sense to support sanitizers in `Release` mode?

This is the corresponding snippet for ASAN:
https://github.com/intel/fpga-runtime-for-opencl/blob/8cd410fe9111a1fc9c7c122f54da1fc21c4fa587/CMakeLists.txt#L190-L201

**Review by pcolberg — CHANGES_REQUESTED** [review]
Thanks @sherry-yuan. How about moving the CMake support into a separate commit? This can be benefitial, e.g., when cherry-picking individual commits later, say for a release branch.

File: test/acl_command_queue_test.cpp (hunk 1 above)
Comment (sherry-yuan) [reply test/acl_command_queue_test.cpp:391]: I checked the asan log, and it seems like this aborted early (so I am not sure). Theoretically since this happen on the same thread, this should be caught by asan as well.

File: CMakeLists.txt (hunk 2 above)
Comment (sherry-yuan) [reply CMakeLists.txt]: Thanks! I have put cmake changes in another PR: https://github.com/intel/fpga-runtime-for-opencl/pull/76 with the suggested change.

File: test/acl_command_queue_test.cpp (hunk 1 above)
Comment (pcolberg) [reply test/acl_command_queue_test.cpp:391]: I cannot find line numbers 390 or 391 in the output of `ctest -V` when TSAN is enabled.

How can this issue be reproduced?

File: test/acl_command_queue_test.cpp [hunk 3]
```diff
@@ -421,8 +419,6 @@ MT_TEST(acl_command_queue, create_with_properties) {
       CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
       CHECK_EQUAL(1, acl_ref_count(cq));
       CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
-      CHECK_EQUAL(0, acl_ref_count(cq));
-      ACL_LOCKED(CHECK(!acl_command_queue_is_valid(cq)));
```
Comment (pcolberg) [inline test/acl_command_queue_test.cpp:425]: Same as above, line numbers 424 or 425 do not appear in TSAN output.

File: test/acl_command_queue_test.cpp [hunk 4]
```diff
@@ -674,15 +670,6 @@ MT_TEST(acl_command_queue, after_context_release) {
...
   CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq1));
-  CHECK_EQUAL(0, acl_ref_count(cq0));
-  CHECK_EQUAL(0, acl_ref_count(cq1));
-
-  ACL_LOCKED(CHECK(!acl_command_queue_is_valid(cq0)));
-  ACL_LOCKED(CHECK(!acl_command_queue_is_valid(cq1)));
-
-  // And once it's gone, it's gone.
-  CHECK_EQUAL(CL_INVALID_COMMAND_QUEUE, clReleaseCommandQueue(cq0));
-  CHECK_EQUAL(CL_INVALID_COMMAND_QUEUE, clReleaseCommandQueue(cq1));
```
Comment (pcolberg) [inline test/acl_command_queue_test.cpp:685]: I have pushed a revised commit which includes the TSAN output for these lines.

**Review by pcolberg — CHANGES_REQUESTED** [review]
Thanks @sherry-yuan! For the changes in `create_with_properties`, how can the issues be reproduced? TSAN seems to pass fine with GCC 7.4.0, are these flagged by ASAN instead?

File: test/acl_command_queue_test.cpp (hunk 1 above)
Comment (sherry-yuan) [reply test/acl_command_queue_test.cpp:391]: The failures should be caught in this workflow: https://github.com/intel/fpga-runtime-for-opencl/runs/5236028155?check_suite_focus=true

TSAN does not catch all issues at once, I remember dealing with tsan issue for first report, and then new issue came up in second run.

Comment (pcolberg) [reply test/acl_command_queue_test.cpp:391]: Thanks @sherry-yuan, rerunning TSAN twice more reproduces all issues.
```diff
diff --git a/test/acl_command_queue_test.cpp b/test/acl_command_queue_test.cpp
index 56f3075..873fb21 100644
--- a/test/acl_command_queue_test.cpp
+++ b/test/acl_command_queue_test.cpp
@@ -387,6 +387,8 @@ MT_TEST(acl_command_queue, create_with_properties) {
     CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
     CHECK_EQUAL(1, acl_ref_count(cq));
     CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
+    CHECK_EQUAL(0, acl_ref_count(cq));
+    ACL_LOCKED(CHECK(!acl_command_queue_is_valid(cq)));
 
     // wait until all threads do their checks on the 0-ref-count command
     // queue before starting the next iteration of the loop and creating new
```
```
6: TEST(acl_command_queue, create_with_properties)==================
6: WARNING: ThreadSanitizer: heap-use-after-free (pid=21508)
6:   Read of size 4 at 0x7b3c000003d4 by main thread:
6:     #0 acl_ref_count<_cl_command_queue*> ../include/acl_util.h:433 (acl_test+0x000000532d77)
6:     #1 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:390 (acl_test+0x000000532d77)
6:     #2 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x000000931a92)
6:     #3 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f86a)
6:     #4 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537d56)
6:     #5 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931f74)
6:     #6 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f7c6)
6:     #7 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f6e4)
6:     #8 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931cb0)
6:     #9 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f669)
6:     #10 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092eb16)
6:     #11 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928e6f)
6:     #12 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928faf)
6:     #13 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x0000009290d6)
6:     #14 main ../test/acl_test.cpp:90 (acl_test+0x00000090ccc6)
6: 
6:   Previous write of size 8 at 0x7b3c000003d0 by main thread (mutexes: write M41):
6:     #0 operator delete(void*) /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_new_delete.cc:71 (libtsan.so.0+0x00000006af04)
6:     #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x00000041118c)
6:     #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x00000041118c)
6:     #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x000000411461)
6:     #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x000000413a1e)
6:     #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x000000413a6e)
6:     #6 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:389 (acl_test+0x000000532c51)
6:     #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x000000931a92)
6:     #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f86a)
6:     #9 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537d56)
6:     #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931f74)
6:     #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f7c6)
6:     #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f6e4)
6:     #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931cb0)
6:     #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f669)
6:     #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092eb16)
6:     #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928e6f)
6:     #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928faf)
6:     #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x0000009290d6)
6:     #19 main ../test/acl_test.cpp:90 (acl_test+0x00000090ccc6)
6: 
6:   Mutex M41 (0x000004dfc600) created at:
6:     #0 pthread_mutex_init /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_interceptors.cc:1117 (libtsan.so.0+0x0000000291fe)
6:     #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x000000928343)
6:     #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x0000004fe4eb)
6:     #3 __libc_csu_init /home/abuild/rpmbuild/BUILD/glibc-2.22/csu/elf-init.c:88 (acl_test+0x000000939a5c)
6: 
6: SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:433 in acl_ref_count<_cl_command_queue*>
6: ==================
6: ==================
6: WARNING: ThreadSanitizer: heap-use-after-free (pid=21508)
6:   Read of size 8 at 0x7b3c000003c8 by main thread (mutexes: write M41):
6:     #0 int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&) ../include/acl_util.h:417 (acl_test+0x000000413780)
6:     #1 acl_command_queue_is_valid(_cl_command_queue*) ../src/acl_command_queue.cpp:553 (acl_test+0x000000413780)
6:     #2 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:391 (acl_test+0x000000532ecc)
6:     #3 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x000000931a92)
6:     #4 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f86a)
6:     #5 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537d56)
6:     #6 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931f74)
6:     #7 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f7c6)
6:     #8 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f6e4)
6:     #9 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931cb0)
6:     #10 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f669)
6:     #11 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092eb16)
6:     #12 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928e6f)
6:     #13 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928faf)
6:     #14 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x0000009290d6)
6:     #15 main ../test/acl_test.cpp:90 (acl_test+0x00000090ccc6)
6: 
6:   Previous write of size 8 at 0x7b3c000003c8 by main thread (mutexes: write M41):
6:     #0 operator delete(void*) /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_new_delete.cc:71 (libtsan.so.0+0x00000006af04)
6:     #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x00000041118c)
6:     #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x00000041118c)
6:     #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x000000411461)
6:     #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x000000413a1e)
6:     #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x000000413a6e)
6:     #6 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:389 (acl_test+0x000000532c51)
6:     #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x000000931a92)
6:     #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f86a)
6:     #9 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537d56)
6:     #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931f74)
6:     #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f7c6)
6:     #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f6e4)
6:     #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931cb0)
6:     #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f669)
6:     #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092eb16)
6:     #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928e6f)
6:     #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928faf)
6:     #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x0000009290d6)
6:     #19 main ../test/acl_test.cpp:90 (acl_test+0x00000090ccc6)
6: 
6:   Mutex M41 (0x000004dfc600) created at:
6:     #0 pthread_mutex_init /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_interceptors.cc:1117 (libtsan.so.0+0x0000000291fe)
6:     #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x000000928343)
6:     #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x0000004fe4eb)
6:     #3 __libc_csu_init /home/abuild/rpmbuild/BUILD/glibc-2.22/csu/elf-init.c:88 (acl_test+0x000000939a5c)
6: 
6: SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:417 in int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&)
6: ==================
```
```diff
diff --git a/test/acl_command_queue_test.cpp b/test/acl_command_queue_test.cpp
index 56f3075..da22605 100644
--- a/test/acl_command_queue_test.cpp
+++ b/test/acl_command_queue_test.cpp
@@ -419,6 +419,8 @@ MT_TEST(acl_command_queue, create_with_properties) {
       CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
       CHECK_EQUAL(1, acl_ref_count(cq));
       CHECK_EQUAL(CL_SUCCESS, clReleaseCommandQueue(cq));
+      CHECK_EQUAL(0, acl_ref_count(cq));
+      ACL_LOCKED(CHECK(!acl_command_queue_is_valid(cq)));
 
       // wait until all threads do their checks on the 0-ref-count command
       // queue before starting the next iteration of the loop and creating new
```
```
6: TEST(acl_command_queue, create_with_properties)==================
6: WARNING: ThreadSanitizer: heap-use-after-free (pid=23129)
6:   Read of size 4 at 0x7b3c000003d4 by main thread:
6:     #0 acl_ref_count<_cl_command_queue*> ../include/acl_util.h:433 (acl_test+0x000000533b09)
6:     #1 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:422 (acl_test+0x000000533b09)
6:     #2 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x0000009318a8)
6:     #3 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f680)
6:     #4 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537b6c)
6:     #5 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931d8a)
6:     #6 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f5dc)
6:     #7 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f4fa)
6:     #8 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931ac6)
6:     #9 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f47f)
6:     #10 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092e92c)
6:     #11 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928c85)
6:     #12 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928dc5)
6:     #13 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x000000928eec)
6:     #14 main ../test/acl_test.cpp:90 (acl_test+0x00000090cadc)
6: 
6:   Previous write of size 8 at 0x7b3c000003d0 by main thread (mutexes: write M41):
6:     #0 operator delete(void*) /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_new_delete.cc:71 (libtsan.so.0+0x00000006af04)
6:     #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x00000041118c)
6:     #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x00000041118c)
6:     #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x000000411461)
6:     #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x000000413a1e)
6:     #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x000000413a6e)
6:     #6 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:421 (acl_test+0x0000005339e6)
6:     #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x0000009318a8)
6:     #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f680)
6:     #9 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537b6c)
6:     #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931d8a)
6:     #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f5dc)
6:     #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f4fa)
6:     #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931ac6)
6:     #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f47f)
6:     #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092e92c)
6:     #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928c85)
6:     #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928dc5)
6:     #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x000000928eec)
6:     #19 main ../test/acl_test.cpp:90 (acl_test+0x00000090cadc)
6: 
6:   Mutex M41 (0x000004dfc600) created at:
6:     #0 pthread_mutex_init /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_interceptors.cc:1117 (libtsan.so.0+0x0000000291fe)
6:     #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x000000928159)
6:     #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x0000004fe4eb)
6:     #3 __libc_csu_init /home/abuild/rpmbuild/BUILD/glibc-2.22/csu/elf-init.c:88 (acl_test+0x00000093987c)
6: 
6: SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:433 in acl_ref_count<_cl_command_queue*>
6: ==================
6: ==================
6: WARNING: ThreadSanitizer: heap-use-after-free (pid=23129)
6:   Read of size 8 at 0x7b3c000003c8 by main thread (mutexes: write M41):
6:     #0 int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&) ../include/acl_util.h:417 (acl_test+0x000000413780)
6:     #1 acl_command_queue_is_valid(_cl_command_queue*) ../src/acl_command_queue.cpp:553 (acl_test+0x000000413780)
6:     #2 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:423 (acl_test+0x000000533c5a)
6:     #3 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x0000009318a8)
6:     #4 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f680)
6:     #5 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537b6c)
6:     #6 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931d8a)
6:     #7 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f5dc)
6:     #8 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f4fa)
6:     #9 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931ac6)
6:     #10 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f47f)
6:     #11 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092e92c)
6:     #12 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928c85)
6:     #13 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928dc5)
6:     #14 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x000000928eec)
6:     #15 main ../test/acl_test.cpp:90 (acl_test+0x00000090cadc)
6: 
6:   Previous write of size 8 at 0x7b3c000003c8 by main thread (mutexes: write M41):
6:     #0 operator delete(void*) /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_new_delete.cc:71 (libtsan.so.0+0x00000006af04)
6:     #1 acl_delete<_cl_command_queue> ../include/acl_support.h:31 (acl_test+0x00000041118c)
6:     #2 acl_free_cl_command_queue ../src/acl_command_queue.cpp:99 (acl_test+0x00000041118c)
6:     #3 acl_delete_command_queue ../src/acl_command_queue.cpp:1005 (acl_test+0x000000411461)
6:     #4 clReleaseCommandQueueIntelFPGA ../src/acl_command_queue.cpp:288 (acl_test+0x000000413a1e)
6:     #5 clReleaseCommandQueue ../src/acl_command_queue.cpp:297 (acl_test+0x000000413a6e)
6:     #6 acl_command_queue_create_with_properties_Test::testBody() ../test/acl_command_queue_test.cpp:421 (acl_test+0x0000005339e6)
6:     #7 Utest::executePlatformSpecificTestBody() ../lib/CppUTest/src/UtestPlatformGcc.cpp:82 (acl_test+0x0000009318a8)
6:     #8 Utest::runInThread() ../lib/CppUTest/src/Utest.cpp:99 (acl_test+0x00000092f680)
6:     #9 acl_command_queue_create_with_properties_Test::runInThreadOnCopy() ../test/acl_command_queue_test.cpp:219 (acl_test+0x000000537b6c)
6:     #10 Utest::executePlatformSpecificRunInThreads() ../lib/CppUTest/src/UtestPlatformGcc.cpp:175 (acl_test+0x000000931d8a)
6:     #11 Utest::run(TestResult&) ../lib/CppUTest/src/Utest.cpp:83 (acl_test+0x00000092f5dc)
6:     #12 Utest::runOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:69 (acl_test+0x00000092f4fa)
6:     #13 Utest::executePlatformSpecificRunOneTest(TestPlugin*, TestResult&) ../lib/CppUTest/src/UtestPlatformGcc.cpp:100 (acl_test+0x000000931ac6)
6:     #14 Utest::runOneTestWithPlugins(TestPlugin*, TestResult&) ../lib/CppUTest/src/Utest.cpp:63 (acl_test+0x00000092f47f)
6:     #15 TestRegistry::runAllTests(TestResult&) ../lib/CppUTest/src/TestRegistry.cpp:72 (acl_test+0x00000092e92c)
6:     #16 CommandLineTestRunner::runAllTests() ../lib/CppUTest/src/CommandLineTestRunner.cpp:105 (acl_test+0x000000928c85)
6:     #17 CommandLineTestRunner::runAllTestsMain() ../lib/CppUTest/src/CommandLineTestRunner.cpp:81 (acl_test+0x000000928dc5)
6:     #18 CommandLineTestRunner::RunAllTests(int, char const**) ../lib/CppUTest/src/CommandLineTestRunner.cpp:63 (acl_test+0x000000928eec)
6:     #19 main ../test/acl_test.cpp:90 (acl_test+0x00000090cadc)
6: 
6:   Mutex M41 (0x000004dfc600) created at:
6:     #0 pthread_mutex_init /nfs/site/disks/swip_pr_1/kbrunham/p4root/depot/devenv/tools/gcc/7.4.0/work/src/libsanitizer/tsan/tsan_interceptors.cc:1117 (libtsan.so.0+0x0000000291fe)
6:     #1 acl_init_condvar ../lib/acl_threadsupport/src/acl_threadsupport.c:330 (acl_test+0x000000928159)
6:     #2 l_global_lock_init ../src/acl_thread.cpp:102 (acl_test+0x0000004fe4eb)
6:     #3 __libc_csu_init /home/abuild/rpmbuild/BUILD/glibc-2.22/csu/elf-init.c:88 (acl_test+0x00000093987c)
6: 
6: SUMMARY: ThreadSanitizer: heap-use-after-free ../include/acl_util.h:417 in int acl_is_valid_ptr<_cl_command_queue*>(_cl_command_queue* const&)
6: ==================
```

File: test/acl_command_queue_test.cpp (hunk 4 above)
Comment (pcolberg) [reply test/acl_command_queue_test.cpp:685]: I am torn on this, but the commit log does get noisy with the entire TSAN output, and you already included most of the output in #71 anyway, so let's keep these longer stack traces in the referenced GitHub issues.

**Review by pcolberg — DISMISSED** [review]

**Review by pcolberg — APPROVED** [review]
